name: Build

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Git Config
        run: |
          git config --global user.email "ci@influct.git"
          git config --global user.name "Influct CI"
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-
      - run: chmod +x gradlew
      - name: Build project
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      - run: gradle applyPatches
      - run: gradle build -x test
      - run: gradle createReobfPaperclipJar
      - name: Upload Paperclip
        uses: actions/upload-artifact@v3
        with:
          name: Paperclip
          path: build/libs/slimeworldmanager-paperclip-*.jar
      - name: Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: plugin/build/libs/*.jar
      - name: Upload Importer
        uses: actions/upload-artifact@v3
        with:
          name: Importer
          path: importer/build/libs/*.jar
      - name: Upload API
        uses: actions/upload-artifact@v3
        with:
          name: API
          path: api/build/libs/*.jar
